name: Deploy Android App to Production

on:
  workflow_dispatch:
    inputs:
      version:
        description: "App Version (e.g., 1.0.0)"
        required: true
        default: "1.0.0"
      build_number:
        description: "Build Number (e.g., 42)"
        required: true
        default: "1"
      # release_notes:
      #   description: "Release Notes"
      #   required: true
      #   default: "Production Release"

jobs:
  deployAndroidProduction:
    runs-on: ubuntu-latest
    env:
      FIREBASE_SERVICE_ACCOUNT: ${{ secrets.FIREBASE_SERVICE_ACCOUNT }}
      RELEASE_SIGNING_KEY: ${{ secrets.RELEASE_SIGNING_KEY }}
      RELEASE_KEYSTORE_PROPERTIES: ${{ secrets.RELEASE_KEYSTORE_PROPERTIES }}
      SUPPLY_KEY: ${{ secrets.SUPPLY_KEY }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup Java
        uses: actions/setup-java@v3
        with:
          distribution: "zulu"
          java-version: "17"

      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: "3.24.5"
          channel: "stable"
          cache: true
        id: flutter

      - name: Setup Ruby and Fastlane
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: "3.3"
          bundler-cache: true

      - name: Decode Android Keystore 
        run: |
          echo "$RELEASE_SIGNING_KEY" > ./android/app/release.keystore.base64
          base64 -d ./android/app/release.keystore.base64 > ./android/app/release.keystore
      
      - name: Set up Supply Key file
        run: |
          echo "$SUPPLY_KEY" > android/fastlane/supply.json
      
      - name: Setup store key properties
        run: echo "$RELEASE_KEYSTORE_PROPERTIES" > android/key.properties

      - name: Build and Deploy to Play Store
        run: |
          cd ./android
          bundle exec fastlane android production version:${{ github.event.inputs.version }} build_number:${{ github.event.inputs.build_number }}
