name: Deploy IOS to Staging

on:
  workflow_dispatch:
    inputs:
      version:
        description: "App Version (e.g., 1.0.0)"
        required: true
        default: "1.0.0"
      build_number:
        description: "Build Number (e.g., 42)"
        required: true
        default: "1"
      release_notes:
        description: "Release Notes"
        required: true
        default: "Initial Release"
      groups:
        description: "TestFlight Tester Groups"
        required: true
        default: "Internal"
      testers:
        description: "TestFlight Testers"
        required: false
        default: ""

jobs:
  deployIOSStaging:
    runs-on: macos-latest
    env:
      APP_STORE_CONNECT_API_KEY: ${{ secrets.APP_STORE_CONNECT_API_KEY }}
      FIREBASE_SERVICE_ACCOUNT : ${{ secrets.FIREBASE_SERVICE_ACCOUNT }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: "3.24.5"
          channel: "stable"
          cache: true
        id: flutter
      - name: Accept Xcode License
        run: sudo xcodebuild -license accept
      - name: Get Packages
        run: flutter pub get
      - name: Setup Fastlane
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: "3.3"
          bundler-cache: true
          working-directory: ios
      - name: Set up Firebase authentication
        run: echo "$FIREBASE_SERVICE_ACCOUNT" >> ./ios/fastlane/service-account.json
      - name: Build and Deploy to Firebase App Distribution
        env:
          MATCH_PASSWORD: ${{ secrets.MATCH_PASSWORD }}
          MATCH_GIT_BASIC_AUTHORIZATION: ${{ secrets.MATCH_GIT_BASIC_AUTHORIZATION }}
        run: |
          cd ./ios
          bundle exec fastlane ios staging version:${{github.event.inputs.version}} build_number:${{github.event.inputs.build_number}} release_notes:${{github.event.inputs.release_notes}} groups:${{github.event.inputs.groups}} testers:${{github.event.inputs.testers}}
